name: Unit Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install OpenCL
        run: sudo apt-get install pocl-opencl-icd
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies.txt
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest
